name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actonlang/setup-acton@v1
        with:
          channel: 'tip'
      - name: "Check out repository code"
        uses: actions/checkout@v4
      - run: acton build
      - run: acton test
      - run: acton test perf

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actonlang/setup-acton@v1
        with:
          channel: 'tip'
      - name: "Check out repository code"
        uses: actions/checkout@v4
      - name: "Cache acton stuff"
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/acton
            out
          key: acton-${{ runner.os }}-${{ runner.arch }}
      - run: acton build
      - uses: actions/upload-artifact@v4
        with:
          name: respnet
          path: out/bin/respnet

  net-test:
    strategy:
      fail-fast: false
      matrix:
        TESTENV: [quicklab, quicklab-crpd, quicklab-notconf]
    runs-on: ubuntu-latest
    env:
      IMAGE_PATH: ${{ vars.IMAGE_PATH }}
    needs: build
    steps:
      - name: Set up env for containers
        run: |
          # IOS XRd
          sudo sysctl -w fs.inotify.max_user_instances=64000
          # cRPD
          sudo apt install linux-modules-extra-$(uname -r)
      - name: "Check out repository code"
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: respnet
          path: out/bin/
      - run: chmod a+x out/bin/respnet
      - name: Login to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: "Start quicklab"
        run: |
          make -C test/${{ matrix.TESTENV }} start wait
      - name: "Configure quicklab"
        run: |
          make -C test/${{ matrix.TESTENV }} copy run-and-configure
      - name: "Run quicklab tests"
        run: |
          timeout 120 bash -c 'until make -C test/${{ matrix.TESTENV }} test; do echo "Retrying..."; sleep 2; done'
